pipeline {
	agent any
	
	stages {
	
		stage ('Compile Stage') {
		
			steps {
					sh '''
					export PATH=$PATH:$MAVEN_HOME/bin
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					mvn clean compile
					'''
			}
		}
		123456789
		stage ('Testing Stage') {
			
			steps {
					sh '''
					export PATH=$PATH:$MAVEN_HOME/bin
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					mvn test'''
			}
			
		}

		stage ('Deployment Stage') {
			
			steps {
					sh '''
					export PATH=$PATH:$MAVEN_HOME/bin
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					mvn deploy'''
			}
			
		}

	}
}