pipeline {
	agent any
	
	stages {
		stage ('Setup Stage') {

			when {
				System.properties['os.name'].contains('Windows')
			}
			steps {
				echo "Windows OS"
			}

		}
		stage ('Compile Stage') {
			steps {
					sh '''
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					$MAVEN_HOME/bin/mvn clean compile
					'''
			}
		}

		stage ('Deployment Stage') {
			
			steps {
					sh '''
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					$MAVEN_HOME/bin/mvn install -DskipTests tomcat7:deploy'''
			}
			
		}
		
		stage ('Testing Stage') {
			
			steps {
					sh '''
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					$MAVEN_HOME/bin/mvn test'''
			}
		}
	}
}