pipeline {
	agent any
	
	stages {

		stage ('Compile Stage') {
			steps {
				script {
					if (isUnix()) {
						sh '''
						cd QEModule_Jenkins_Pipeline_Servlet_Selenium
						$MAVEN_HOME/bin/mvn clean compile
						'''
					} else {
						bat '''
						cd QEModule_Jenkins_Pipeline_Servlet_Selenium_Windows
						%MAVEN_HOME%/bin/mvn clean compile
						'''
					}
				}
			}
		}

		stage ('Deployment Stage') {
			
			steps {
					sh '''
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					$MAVEN_HOME/bin/mvn install -DskipTests tomcat7:deploy'''
			}
			
		}
		
		stage ('Testing Stage') {
			
			steps {
					sh '''
					cd QEModule_Jenkins_Pipeline_Servlet_Selenium
					$MAVEN_HOME/bin/mvn test'''
			}
		}
	}
}